#include "PluginEditor.h"
#include <cmath>
static const auto bg=juce::Colour(0xff021217),panel=juce::Colour(0xff05272d),cyan=juce::Colour(0xff55ffe2),blue=juce::Colour(0xff4d9fff);
void NebulaLookAndFeel::drawRotarySlider(juce::Graphics& g,int x,int y,int w,int h,float pos,float start,float end,juce::Slider&)
{
    auto r=juce::Rectangle<float>((float)x,(float)y,(float)w,(float)h).reduced(8);float rad=juce::jmin(r.getWidth(),r.getHeight())*.5f;auto c=r.getCentre();
    g.setColour(juce::Colour(0xff01090d));g.fillEllipse(r);g.setColour(juce::Colour(0xff176775));g.drawEllipse(r,2);
    juce::Path arc;arc.addCentredArc(c.x,c.y,rad-2,rad-2,0,start,start+pos*(end-start),true);g.setColour(cyan.withAlpha(.16f));g.drawEllipse(r.expanded(5),6);g.setColour(cyan.withAlpha(.30f));g.drawEllipse(r.expanded(2),3);g.setColour(cyan);g.strokePath(arc,juce::PathStrokeType(3));
    float a=start+pos*(end-start);juce::Path tick;tick.startNewSubPath(c);tick.lineTo(c+juce::Point<float>(std::sin(a),-std::cos(a))*(rad-9));g.setColour(juce::Colours::white);g.strokePath(tick,juce::PathStrokeType(2));
}
AstrophiluxNebulaAudioProcessorEditor::AstrophiluxNebulaAudioProcessorEditor(AstrophiluxNebulaAudioProcessor& p):AudioProcessorEditor(&p),processor(p),keyboard(p.keyboardState,juce::MidiKeyboardComponent::horizontalKeyboard)
{
    hero=juce::ImageFileFormat::loadFrom(BinaryData::Infinity_png,BinaryData::Infinity_pngSize);
    for(size_t i=0;i<knobs.size();++i){auto& k=knobs[i];k.setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);k.setTextBoxStyle(juce::Slider::TextBoxBelow,false,70,18);k.setLookAndFeel(&look);k.setColour(juce::Slider::textBoxTextColourId,juce::Colour(0xffd8ffff));k.setColour(juce::Slider::textBoxBackgroundColourId,juce::Colour(0xff03171c));addAndMakeVisible(k);labels[i].setText(names[i],juce::dontSendNotification);labels[i].setJustificationType(juce::Justification::centred);labels[i].setColour(juce::Label::textColourId,juce::Colour(0xffd9ffff));labels[i].setFont(10.f);addAndMakeVisible(labels[i]);attachments.push_back(std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(processor.state,ids[i],k));}
    for(auto* box:{&waveABox,&waveBBox}){box->addItem("Saw",1);box->addItem("Square",2);box->addItem("Triangle",3);box->addItem("Sine",4);addAndMakeVisible(*box);}waveAAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(processor.state,"waveA",waveABox);waveBAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(processor.state,"waveB",waveBBox);
    presetBox.addSectionHeading("SYNTH PADS");for(int i=0;i<6;++i)presetBox.addItem(processor.getProgramName(i),i+1);presetBox.addSeparator();presetBox.addSectionHeading("SYNTHWAVE");for(int i=6;i<12;++i)presetBox.addItem(processor.getProgramName(i),i+1);presetBox.setSelectedId(processor.getPresetIndex()+1,juce::dontSendNotification);presetBox.onChange=[this]{processor.loadPreset(presetBox.getSelectedId()-1);};addAndMakeVisible(presetBox);
    auto movePreset=[this](int d){int i=(presetBox.getSelectedId()-1+d+12)%12;presetBox.setSelectedId(i+1,juce::sendNotification);};previous.onClick=[movePreset]{movePreset(-1);};next.onClick=[movePreset]{movePreset(1);};addAndMakeVisible(previous);addAndMakeVisible(next);
    keyboard.setAvailableRange(24,96);keyboard.setKeyWidth(22.f);keyboard.setScrollButtonsVisible(false);keyboard.setColour(juce::MidiKeyboardComponent::whiteNoteColourId,juce::Colour(0xffe9ffff));keyboard.setColour(juce::MidiKeyboardComponent::blackNoteColourId,juce::Colour(0xff031116));keyboard.setColour(juce::MidiKeyboardComponent::keyDownOverlayColourId,cyan);addAndMakeVisible(keyboard);
    setResizable(true,true);setResizeLimits(1000,650,1600,1000);setSize(1400,860);startTimerHz(30);
}
AstrophiluxNebulaAudioProcessorEditor::~AstrophiluxNebulaAudioProcessorEditor(){for(auto& k:knobs)k.setLookAndFeel(nullptr);}
void AstrophiluxNebulaAudioProcessorEditor::timerCallback(){animation+=.025f;if(animation>juce::MathConstants<float>::twoPi)animation=0;repaint();}
void AstrophiluxNebulaAudioProcessorEditor::drawPanel(juce::Graphics& g,juce::Rectangle<float> r,const juce::String& t,juce::Colour a){g.setColour(panel.withAlpha(.96f));g.fillRoundedRectangle(r,10);g.setColour(a.withAlpha(.45f));g.drawRoundedRectangle(r,10,1.2f);g.setColour(a);g.setFont(juce::FontOptions(12.f,juce::Font::bold));g.drawText(t,r.toNearestInt().reduced(14).removeFromTop(24),juce::Justification::centredLeft);}
void AstrophiluxNebulaAudioProcessorEditor::drawWave(juce::Graphics& g,juce::Rectangle<float> r,juce::Colour c,float ph){g.setColour(juce::Colour(0xff0b3b43));for(int i=1;i<8;i++)g.drawVerticalLine((int)(r.getX()+r.getWidth()*i/8),r.getY(),r.getBottom());juce::Path p;for(int x=0;x<(int)r.getWidth();++x){float t=(float)x/r.getWidth()*juce::MathConstants<float>::twoPi*2.2f;float yy=r.getCentreY()+std::sin(t+ph+animation)*r.getHeight()*.25f;if(x==0)p.startNewSubPath(r.getX()+x,yy);else p.lineTo(r.getX()+x,yy);}g.setColour(c.withAlpha(.18f));for(int i=-3;i<=3;i++){auto q=p;q.applyTransform(juce::AffineTransform::translation(0,(float)i*3));g.strokePath(q,juce::PathStrokeType(1));}g.setColour(c);g.strokePath(p,juce::PathStrokeType(2));}
void AstrophiluxNebulaAudioProcessorEditor::paint(juce::Graphics& g)
{
    g.fillAll(bg);int W=getWidth(),H=getHeight();if(hero.isValid()){g.setOpacity(.22f);g.drawImage(hero,juce::Rectangle<float>(0,0,(float)W,(float)H),juce::RectanglePlacement::fillDestination);g.setOpacity(1);}
    juce::ColourGradient grad(juce::Colour(0xd9002026),0,0,juce::Colour(0xf0020d14),(float)W,(float)H,false);g.setGradientFill(grad);g.fillAll();
    g.setColour(cyan);g.setFont(juce::FontOptions(12.f,juce::Font::bold));g.drawText("A S T R O P H I L U X",28,18,300,20,juce::Justification::centredLeft);g.setFont(juce::FontOptions(34.f));g.drawText("N E B U L A",28,39,330,45,juce::Justification::centredLeft);g.setFont(10.f);g.setColour(juce::Colour(0xffb9eeee));g.drawText("INSTRUMENTS FOR FURTHER PLACES",30,84,320,18,juce::Justification::centredLeft);
    g.setColour(juce::Colour(0xff80fff1));g.setFont(10.f);g.drawText("SYNTH PADS  /  ASTROPHILUX LIBRARY",getWidth()/2-180,92,360,18,juce::Justification::centred);
    int side=205,top=125,bottom=150;auto sideR=juce::Rectangle<float>(12,(float)top,(float)side,H-top-bottom-10);drawPanel(g,sideR,"PRESET LIBRARY",cyan);
    const char* lib[]={"SYNTH PADS","  Starlight Bloom","  Infinity Choir","  Pixel Memory","  Glass Comet","  Aurora Lift","  Afterglow","SYNTHWAVE","  Neon Highway","  Midnight Arcade","  Chrome Horizon","  Cassette Sunset","  Night Drive","  Digital Hearts"};for(int i=0;i<14;i++){g.setColour((i==0||i==7)?cyan:juce::Colour(0xffc6edf0));g.setFont((i==0||i==7)?juce::FontOptions(11.f,juce::Font::bold):juce::FontOptions(11.f));g.drawText(lib[i],30,165+i*27,170,22,juce::Justification::centredLeft);}
    auto main=juce::Rectangle<float>((float)side+25,(float)top,(float)W-side-37,(float)H-top-bottom-10);float y=top+8,half=(main.getWidth()-10)/2;auto oa=juce::Rectangle<float>(main.getX(),y,half,190),ob=juce::Rectangle<float>(main.getX()+half+10,y,half,190);drawPanel(g,oa,"OSCILLATOR A  /  REAL SYNTH",cyan);drawPanel(g,ob,"OSCILLATOR B  /  REAL SYNTH",blue);drawWave(g,oa.reduced(15).withTrimmedTop(28).withTrimmedBottom(20),cyan,0);drawWave(g,ob.reduced(15).withTrimmedTop(28).withTrimmedBottom(20),blue,1.1f);
    auto env=juce::Rectangle<float>(main.getX(),y+200,main.getWidth()*.62f,190),fil=juce::Rectangle<float>(env.getRight()+10,y+200,main.getRight()-env.getRight()-10,190);drawPanel(g,env,"AMP ENVELOPE",cyan);drawPanel(g,fil,"FILTER  /  TONE",blue);
    auto graph=env.reduced(18).withTrimmedTop(30).withTrimmedBottom(75);juce::Path ep;ep.startNewSubPath(graph.getX(),graph.getBottom());ep.lineTo(graph.getX()+graph.getWidth()*.2f,graph.getY()+5);ep.lineTo(graph.getX()+graph.getWidth()*.48f,graph.getCentreY());ep.lineTo(graph.getX()+graph.getWidth()*.72f,graph.getCentreY());ep.lineTo(graph.getRight(),graph.getBottom());g.setColour(cyan);g.strokePath(ep,juce::PathStrokeType(2));
    auto fg=fil.reduced(18).withTrimmedTop(35).withTrimmedBottom(75);juce::Path fp;fp.startNewSubPath(fg.getX(),fg.getY()+12);for(int x=0;x<(int)fg.getWidth();++x){float t=(float)x/fg.getWidth();fp.lineTo(fg.getX()+x,fg.getY()+12+60*std::pow(t,4.f));}g.setColour(blue);g.strokePath(fp,juce::PathStrokeType(2));
    float fxY=y+400,fw=(main.getWidth()-20)/3;drawPanel(g,{main.getX(),fxY,fw,112},"DRIFT  /  MOVEMENT",cyan);drawPanel(g,{main.getX()+fw+10,fxY,fw,112},"ECHO  /  DELAY",blue);drawPanel(g,{main.getX()+2*(fw+10),fxY,fw,112},"SPACE  /  REVERB",juce::Colour(0xff65e0b5));
    g.setColour(juce::Colour(0xff43d8ca));g.setFont(9.f);g.drawText("v0.6  |  CLICK THE KEYBOARD TO PLAY  |  ALL KNOBS EXPOSED TO DAW AUTOMATION",20,H-18,W-40,12,juce::Justification::centred);
}
void AstrophiluxNebulaAudioProcessorEditor::resized()
{
    int W=getWidth(),H=getHeight(),side=205,top=125,bottom=150;previous.setBounds(W/2-225,43,38,40);presetBox.setBounds(W/2-180,43,360,40);next.setBounds(W/2+187,43,38,40);labels[8].setBounds(W-155,20,100,16);knobs[8].setBounds(W-150,36,90,80);
    float mainX=side+25,mw=W-side-37,y=top+8,envY=y+200,envW=mw*.62f;float half=(mw-10)/2;waveABox.setBounds((int)mainX+18,(int)y+36,145,28);waveBBox.setBounds((int)(mainX+half+10)+18,(int)y+36,145,28);auto place=[&](int i,float x,float yy,float w=78.f){labels[(size_t)i].setBounds((int)x,(int)yy-14,(int)w,14);knobs[(size_t)i].setBounds((int)x,(int)yy,(int)w,82);};for(int i=0;i<4;i++)place(i,mainX+28+i*(envW-90)/3,envY+102);place(9,mainX+half-205,y+92);place(10,mainX+half+35,y+92);place(11,mainX+mw-120,y+92);place(4,mainX+envW+85,envY+102);float fxY=y+400,fw=(mw-20)/3;place(5,mainX+fw*.5f-38,fxY+25);place(6,mainX+fw+10+fw*.5f-38,fxY+25);place(7,mainX+2*(fw+10)+fw*.5f-38,fxY+25);
    keyboard.setBounds(20,H-bottom+18,W-40,105);
}